apiVersion: v1
kind: Pod
metadata:
  name: file-browser
spec:
  containers:
    - name: file-browser
      image: busybox
      command: ["sleep", "600"]
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: openfold3-storage
  restartPolicy: Never